---
title: "Project_final_stats101c"
output: pdf_document
date: "2023-11-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ISLR)
library(ggplot2)
library(MASS)
library(stringr)
library(schoolmath)
library(ggfortify)
library(lattice)
library(tidyverse)
library(caret)
require(boot)
library(crossval)
library(mice)
library(glmnet)
library(randomForest)
library(ClusterR)
library(nnet)
library(cluster)
library(Rtsne)
library(neuralnet)
```


# 1
```{r}

train.data <- read.csv("TrainSAData2.csv",stringsAsFactors=F)
test.data <- read.csv("TestSAData2NoY.csv",stringsAsFactors=F)


dim(train.data)
dim(test.data)


train.data$sex <- as.factor(train.data[,2])
train.data$hear_left <- as.factor(train.data[,9])
train.data$hear_right <- as.factor(train.data[,10])
train.data$BMI.Category <- as.factor(train.data[,25])
train.data$AGE.Category <- as.factor(train.data[,26])
train.data$Smoking.Status <- as.factor(train.data[,27])
train.data$Alcoholic.Status <- as.factor(train.data[,28])

test.data$sex <- as.factor(test.data[,2])
test.data$hear_left <- as.factor(test.data[,9])
test.data$hear_right <- as.factor(test.data[,10])
test.data$BMI.Category <- as.factor(test.data[,25])
test.data$AGE.Category <- as.factor(test.data[,26])
test.data$Smoking.Status <- as.factor(test.data[,27])

```

# Dealing with missing data.
- Remove NAs.

# 2
```{r}
imp.train.data <- mice(train.data,m=1,maxit=1,method='rf',seed=0726)

```
# 3
```{r}
imp.test.data <- mice(test.data,m=1,maxit=1,method='rf',seed=0726)

```
# 4
```{r}
comp.train.data <- mice::complete(imp.train.data,1)
comp.train.data
comp.test.data <- mice::complete(imp.test.data,1)
comp.test.data
```













# Starting here Neural Network
```{r}
imputed_train_data <- comp.train.data
imputed_test_data <- comp.test.data


scale_train_data <- scale(imputed_train_data[, c(3, 4, 5, 6, 7, 8, 11, 12,13,14,15,16,17,18,20,21,22,23,24)])

scale_test_data <- scale(imputed_test_data[, c(3, 4, 5, 6, 7, 8, 11, 12,13,14,15,16,17,18,20,21,22,23,24)])

train_data <- cbind(scale_train_data,imputed_train_data[,c(2,9,10,19,25,26,27,28)])


test_data <- cbind(scale_test_data,imputed_test_data[,c(2,9,10,19,25,26,27)])

train <- train_data
test <- test_data
```



```{r}
train_data <- comp.train.data
test_data <- comp.test.data

train_data$sex <- ifelse(train_data$sex=="Male",1,0)
train_data$hear_left <- ifelse(train_data$hear_left=="Normal",1,0)
train_data$hear_right <- ifelse(train_data$hear_right=="Normal",1,0)

train_data$BMI.Category <- as.double(unclass(as.factor(train_data$BMI.Category)))
#  "Healthy"     "Obese"       "Overweight"  "Underweight" (1,2,3,4)


train_data$AGE.Category <- as.double(unclass(as.factor(train_data$AGE.Category)))

# "Mid-aged" "Old"      "Very Old" "Young"   (1,2,3,4)


train_data$Smoking.Status <- as.double(unclass(as.factor(train_data$Smoking.Status)))
# "Never Smoked"  "Still Smoking" "Used to Smoke" (1,2,3)


train_data[,27]<-ifelse(train_data$Alcoholic.Status=="Y",1,0)

# "Y","N".   1,0

test_data$sex <- ifelse(test_data$sex=="Male",1,0)
test_data$hear_left <- ifelse(test_data$hear_left=="Normal",1,0)
test_data$hear_right <- ifelse(test_data$hear_right=="Normal",1,0)

test_data$BMI.Category <- as.double(unclass(as.factor(test_data$BMI.Category)))
#  "Healthy"     "Obese"       "Overweight"  "Underweight" (1,2,3,4)


test_data$AGE.Category <- as.double(unclass(as.factor(test_data$AGE.Category)))

# "Mid-aged" "Old"      "Very Old" "Young"   (1,2,3,4)


test_data$Smoking.Status <- as.double(unclass(as.factor(test_data$Smoking.Status)))
# "Never Smoked"  "Still Smoking" "Used to Smoke" (1,2,3)
```


```{r}
str(train_data)
```





```{r}
set.seed(0726)
S.train=sample(1:nrow(train_data), 65000) 

T.train=train_data[S.train,]
T.test=train_data[-S.train,] 

dim(T.train);dim(T.test)
```

```{r}
xtrain <- T.train[,-27]
ytrain <- T.train$Alcoholic.Status
dim(ytrain) <- c(length(ytrain), 1)


xtest <- T.test[,-27]
ytest <- T.test$Alcoholic.Status
dim(ytest) <- c(length(ytest), 1) 
```



```{r}
xtrain <- as.matrix(xtrain, byrow=TRUE)
xtrain <- t(xtrain)
ytrain <- as.matrix(ytrain, byrow=TRUE)
ytrain <- t(ytrain)

xtest <- as.matrix(xtest, byrow=TRUE)
xtest <- t(xtest)
ytest <- as.matrix(ytest, byrow=TRUE)
ytest <- t(ytest)


```



```{r}
# Find the size of each layer (Input, hidden, output). 
getLayerSize <- function(x, y, hidneu, train=TRUE) {
  numx <- dim(x)[1]
  numh <- hidneu
  numy <- dim(y)[1]   
  
  size <- list("number of imput" = numx,
               "number of hidden" = numh,
               "number of output" = numy)
  
  return(size)
}


layer_size <- getLayerSize(xtrain, ytrain, 21)
layer_size


getLayerSize1 <- function(x, hidneu, train=TRUE) {
  numx <- dim(x)[1]
  numh <- hidneu
    
  
  size <- list("number of imput" = numx,
               "number of hidden" = numh,
               )
  
  return(size)
}
```

```{r}
initializeParameters <- function(x, list_layer_size){

    mat <- dim(data.matrix(x))[2]
    
    numx <- list_layer_size$`number of imput`
    numh <- list_layer_size$`number of hidden`
    numy <- list_layer_size$`number of output`
        
    W1 <- matrix(runif(numh * numx), nrow = numh, ncol = numx, byrow = TRUE) * 0.01
    b1 <- matrix(rep(0, numh), nrow = numh)
    W2 <- matrix(runif(numy * numh), nrow = numy, ncol = numh, byrow = TRUE) * 0.01
    b2 <- matrix(rep(0, numy), nrow = numy)
    
    params <- list("W1" = W1,
                   "b1" = b1, 
                   "W2" = W2,
                   "b2" = b2)
    
    return (params)
}


init_params <- initializeParameters(xtrain, layer_size)
lapply(init_params, function(x) dim(x))
```

```{r}
sigmoid <- function(x){
    return(1 / (1 + exp(-x)))
}
```



```{r}
forwardPropagation <- function(X,list_layer_size,para){
    
    mat <- dim(X)[2]
    numh <- list_layer_size$`number of hidden`
    numy <- list_layer_size$`number of output`
    
    W1 <- para$W1
    b1 <- para$b1
    W2 <- para$W2
    b2 <- para$b2
    
    b1n <- matrix(rep(b1, mat), nrow = numh)
    b2n <- matrix(rep(b2, mat), nrow = numy)
    
    Z1 <- W1%*%X+b1n
    A1 <- tanh(Z1)
    Z2 <- W2%*%A1+b2n
    A2 <- sigmoid(Z2)
    
    cache <- list("Z1" = Z1,
                  "A1" = A1, 
                  "Z2" = Z2,
                  "A2" = A2)

    return (cache)
}

fwd_prop <- forwardPropagation(xtrain, layer_size, init_params)
lapply(fwd_prop, function(x) dim(x))


```


```{r}
computeCost <- function(X, y, cac) {
    m <- dim(X)[2]
    A2 <- cac$A2
    logpr <- (log(A2)*y)+(log(1-A2)*(1-y))
    c <- -sum(logpr/m)
    return (c)
}
cost <- computeCost(xtrain, ytrain, fwd_prop)
cost
```



```{r}
backwardPropagation <- function(X, y, cac, para, list_layer_size){
    
    mat <- dim(X)[2]
    
    numx <- list_layer_size$`number of imput`
    numh <- list_layer_size$`number of hidden`
    numy <- list_layer_size$`number of output`

    A2 <- cac$A2
    A1 <- cac$A1
    W2 <- para$W2

    dZ2 <- A2-y
    dW2 <- 1/mat*(dZ2%*%t(A1)) 
    db2 <- matrix(1/mat*sum(dZ2), nrow = numy)
    db2_new <- matrix(rep(db2, mat), nrow = numy)
    
    dZ1 <- (t(W2)%*%dZ2)*(1-A1^2)
    dW1 <- (1/mat)*(dZ1%*%t(X))
    db1 <- matrix(1/mat*sum(dZ1), nrow = numh)
    db1_new <- matrix(rep(db1, mat), nrow = numh)
    
    gradient <- list("dW1" = dW1, 
                  "db1" = db1,
                  "dW2" = dW2,
                  "db2" = db2)
    
    return(gradient)
}

back_prop <- backwardPropagation(xtrain, ytrain, fwd_prop, init_params, layer_size)
lapply(back_prop, function(x) dim(x))

```


```{r}
updateParameters <- function(gradient, para, learning_rate){

    W1 <- para$W1
    b1 <- para$b1
    W2 <- para$W2
    b2 <- para$b2
    
    dW1 <- gradient$dW1
    db1 <- gradient$db1
    dW2 <- gradient$dW2
    db2 <- gradient$db2
    
    
    W1 <- W1 - learning_rate*dW1
    b1 <- b1 - learning_rate*db1
    W2 <- W2 - learning_rate*dW2
    b2 <- b2 - learning_rate*db2
    
    updated_params <- list("W1" = W1,
                           "b1" = b1,
                           "W2" = W2,
                           "b2" = b2)
    
    return (updated_params)
}

update_params <- updateParameters(back_prop, init_params, learning_rate = 0.71)
lapply(update_params, function(x) dim(x))

```


```{r}
trainModel <- function(X, y, num_iteration, hidden_neurons, lr){
    
    layer_size <- getLayerSize(X, y, hidden_neurons)
    init_params <- initializeParameters(X, layer_size)
    cost_history <- c()
    for (i in 1:num_iteration) {
        fwd_prop <- forwardPropagation(X, layer_size, init_params)
        cost <- computeCost(X, y, fwd_prop)
        back_prop <- backwardPropagation(X, y, fwd_prop, init_params, layer_size)
        update_params <- updateParameters(back_prop, init_params, learning_rate = lr)
        init_params <- update_params
        cost_history <- c(cost_history, cost)
        
        if (i %% 100 == 0) cat("Iteration", i, " | Cost: ", cost, "\n")
    }
    
    model_out <- list("updated_params" = update_params,
                      "cost_hist" = cost_history)
    return (model_out)
}

```

```{r}

EPOCHS = 4000
HIDDEN_NEURONS = 21     # the lowest loss 
LEARNING_RATE = 0.7

train_model <- trainModel(xtrain, ytrain, hidden_neurons = HIDDEN_NEURONS, num_iteration = EPOCHS, lr = LEARNING_RATE)
```



```{r}
makePrediction <- function(X, y, hidden_neurons){
    layer_size <- getLayerSize(X, y, hidden_neurons)
    params <- train_model$updated_params
    fwd_prop <- forwardPropagation(X, layer_size, params)
    pred <- fwd_prop$A2
    
    return (pred)
}

makePrediction1 <- function(X, hidden_neurons){
    layer_size <- getLayerSize1(X, hidden_neurons)
    params <- train_model$updated_params
    fwd_prop <- forwardPropagation(X, layer_size, params)
    pred <- fwd_prop$A2
    
    return (pred)
}

y_pred <- makePrediction(xtest, ytest, HIDDEN_NEURONS)
y_pred <- round(y_pred)


tb_nn <- table(ytest, y_pred)

cat("NN accuracy : \n")

mean(ytest==y_pred)
```


```{r}
fintest <- as.matrix(test_data, byrow=TRUE)
fintest <- t(fintest)

y_pred1 <- makePrediction1(fintest, HIDDEN_NEURONS)
y_pred1 <- round(y_pred1)

y_pred1 <- as.numeric(y_pred1[1,])

y_pred1 <- ifelse(y_pred1==1,"Y","N")

write.csv(data.frame("ID"=c(1:30000),"Alcoholic.Status"=y_pred1),row.names = FALSE,"/Users/tsukasamiyaji/Desktop/R/prediction_nn.csv")
```


















# 5
```{r}
train_data <- comp.train.data
test_data <- comp.test.data

train_data$sex <- ifelse(train_data$sex=="Male",1,0)
train_data$hear_left <- ifelse(train_data$hear_left=="Normal",1,0)
train_data$hear_right <- ifelse(train_data$hear_right=="Normal",1,0)

train_data$BMI.Category <- as.double(unclass(as.factor(train_data$BMI.Category)))
#  "Healthy"     "Obese"       "Overweight"  "Underweight" (1,2,3,4)


train_data$AGE.Category <- as.double(unclass(as.factor(train_data$AGE.Category)))

# "Mid-aged" "Old"      "Very Old" "Young"   (1,2,3,4)


train_data$Smoking.Status <- as.double(unclass(as.factor(train_data$Smoking.Status)))
# "Never Smoked"  "Still Smoking" "Used to Smoke" (1,2,3)


train_data[,27]<-ifelse(train_data$Alcoholic.Status=="Y",1,0)

# "Y","N".   1,0

test_data$sex <- ifelse(test_data$sex=="Male",1,0)
test_data$hear_left <- ifelse(test_data$hear_left=="Normal",1,0)
test_data$hear_right <- ifelse(test_data$hear_right=="Normal",1,0)

test_data$BMI.Category <- as.double(unclass(as.factor(test_data$BMI.Category)))
#  "Healthy"     "Obese"       "Overweight"  "Underweight" (1,2,3,4)


test_data$AGE.Category <- as.double(unclass(as.factor(test_data$AGE.Category)))

# "Mid-aged" "Old"      "Very Old" "Young"   (1,2,3,4)


test_data$Smoking.Status <- as.double(unclass(as.factor(test_data$Smoking.Status)))
# "Never Smoked"  "Still Smoking" "Used to Smoke" (1,2,3)
```



# 6
```{r}
train_data <- train_data[,-c(1,28)]
test_data <- test_data[,-c(1)]
# Load necessary library
library(knitr)

# Assuming train_data is your data frame
# Convert all columns that should be numeric but are not
numeric_columns <- sapply(train_data, is.numeric)

# If there are factors that represent numbers, convert them to numeric
factor_columns <- sapply(train_data, is.factor)
train_data[factor_columns] <- lapply(train_data[factor_columns], function(x) as.numeric(as.character(x)))

# Now exclude all non-numeric columns
train_data_numeric <- train_data[ , numeric_columns]

# Check for NA values and handle them
train_data_numeric <- na.omit(train_data_numeric) # Or another method of your choice

# Now you can compute the correlation matrix
cor_matrix <- cor(train_data_numeric)

# Initialize an empty data frame to store results
results <- data.frame(row = character(), column = character(), p = numeric())


# Loop through the correlation matrix and perform the test
for(i in 1:nrow(cor_matrix)) {
for(j in i:nrow(cor_matrix)) {
if(i != j) { # Avoid self-correlation
test_result <- cor.test(train_data_numeric[,i], train_data_numeric[,j])
results <- rbind(results, data.frame(row = names(train_data_numeric)[i], column = names(train_data_numeric)[j], p = test_result$p.value))
}
}
}

# Sort results by p-value
results <- results[order(results$p), ]

# Display the table
kable(results)

```






